#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

  oracle_asm_usage - Munin plugin to monitor Oracle ASM Disk Group Usage

=head1 CONFIGURATION

  The following shows example settings for this plugin:

  [oracle_asm_*]
     user  grid
     env.oracle_auth  / as SYSASM
     env.ORACLE_HOME  /path/to/grid/home/version
     env.ORACLE_SID   SOMESID

=head1 NOTES

  Uses the command "sqlplus".
  Tested with Oracle Database 12c R1.

=head1 AUTHOR

  K.Cima https://github.com/shakemid

=head1 LICENSE

  GPLv2

=cut

# Magic markers
#%# family=contrib
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

# Environments
: ${oracle_auth:=/ as SYSASM}
: ${ORACLE_SID:=+ASM}
: ${ORACLE_HOME:=/opt/grid/home/*}

PATH=$PATH:$ORACLE_HOME/bin
export PATH ORACLE_HOME ORACLE_SID

# Graph settings
fields=()
labels=()
types=()
draws=()
type_default=GAUGE
draw_default=LINE
: ${warning:=90}
: ${critical:=95}


autoconf() {
    if [ -x $( which sqlplus ) ]; then
        echo yes
    else
        echo no
    fi
    exit 0
}

config() {
    echo graph_title Oracle ASM Disk Group Usage
    echo graph_info Oracle ASM Disk Group Usage
    echo graph_category Oracle
    echo graph_args --base 1000 --lower-limit 0 --upper-limit 100 --rigid
    echo graph_vlabel %
    #echo graph_scale no
    echo graph_order ${fields[@]}
    echo warning $warning
    echo critical $critical

    i=0
    for field in ${fields[@]}
    do
        echo ${field}.label ${labels[$i]}
        echo ${field}.type  ${types[$i]}
        echo ${field}.draw  ${draws[$i]}
        i=$((i+1))
    done
 
    exit 0
}

getfield() {
    local line
    while read line
    do
        fields+=( "$line" )
        labels+=( "$line" )
        types+=( $type_default )
        draws+=( $draw_default )
    done < <( sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'
set pagesize 0
set linesize 256
set numwidth 30
set feedback off
SELECT
   name
FROM
   v\$asm_diskgroup 
ORDER BY
   name;
EOF
)

}

getvalue() {
    sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'
set pagesize 0
set feedback off
set linesize 256
set numwidth 30
SELECT
   name || '.value ' || round( ( total_mb - free_mb ) / total_mb * 100 )  
FROM
   v\$asm_diskgroup 
ORDER BY
   name;
EOF
  
    exit 0
}

# main
case $1 in
autoconf)
    autoconf
    ;;
config)
    getfield
    config
    ;;
*)
    getvalue
    ;;
esac
