#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

  oracle_event_wait_userio - Munin plugin to monitor Oracle Wait Event Statistics

=head1 CONFIGURATION

  The following shows example settings for this plugin:

  [oracle_*]
     user  oracle
     env.oracle_auth  / as SYSDBA
     env.ORACLE_HOME  /path/to/oracle/product/version
     env.ORACLE_SID   SOMESID

=head1 NOTES

  Uses the command "sqlplus".
  Tested with Oracle Database 12c R1.

=head1 AUTHOR

  K.Cima https://github.com/shakemid

=head1 LICENSE

  GPLv2

=cut

# Magic markers
#%# family=contrib
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

# Environments
: ${oracle_auth:=/ as SYSDBA}
: ${ORACLE_SID:=orcl}
: ${ORACLE_HOME:=$( echo /opt/oracle/product/* )}

PATH=$PATH:$ORACLE_HOME/bin
export PATH ORACLE_HOME ORACLE_SID

# Graph settings
fields=(
    wait_parameter_file_io
    wait_disk_file_operations_io
    wait_data_file_init_write
    wait_local_write_wait
    wait_read_by_other_session
    wait_db_file_sequential_read
    wait_db_file_scattered_read
    wait_db_file_single_write
    wait_db_file_parallel_read
    wait_direct_path_read
    wait_direct_path_read_temp
    wait_direct_path_write
    wait_direct_path_write_temp
    wait_external_table_read
    wait_external_table_write
    wait_external_table_open
)

# memo: select event from v$system_event where wait_class = 'User I/O' order by event;

labels=(
    'Parameter File I/O'
    'Disk file operations I/O'
    'Data file init write'
    'local write wait'
    'read by other session'
    'db file sequential read'
    'db file scattered read'
    'db file single write'
    'db file parallel read'
    'direct path read'
    'direct path read temp'
    'direct path write'
    'direct path write temp'
    'external table read'
    'external table write'
    'external table open'
)

types=(
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
)

draws=(
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
)


autoconf() {
    if [ -x $( which sqlplus ) ]; then
        echo yes
    else
        echo no
    fi
    exit 0
}

config() {
    echo graph_title Oracle Wait Event - User I/O
    echo graph_category Oracle
    echo graph_args --base 1000 --lower-limit 0 --rigid
    echo graph_vlabel microseconds
    echo graph_info Oracle Wait Event - User I/O
    #echo graph_scale no
    echo graph_order ${fields[@]} 

    i=0
    for field in ${fields[@]}
    do
        echo ${field}.label ${labels[$i]}
        echo ${field}.type ${types[$i]}
        echo ${field}.draw ${draws[$i]}
        i=$((i+1))
    done
 
    exit 0
}

getvalue() {
    i=0
    for field in ${fields[@]}
    do
        sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'
set pagesize 0
set linesize 256
set numwidth 30
set feedback off
SELECT
  '${field}.value ' || time_waited_micro
FROM
  v\$system_event
WHERE
  event = '${labels[$i]}';
EOF
        i=$((i+1))
    done
  
    exit 0
}

case $1 in
autoconf)
    autoconf
    ;;
config)
    config
    ;;
*)
    getvalue
    ;;
esac
