#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

  oracle_event_wait_cuncurrency - Munin plugin to monitor Oracle Wait Event Statistics

=head1 CONFIGURATION

  The following shows example settings for this plugin:

  [oracle_*]
     user  oracle
     env.oracle_auth  / as SYSDBA
     env.ORACLE_HOME  /path/to/oracle/product/version
     env.ORACLE_SID   SOMESID

=head1 NOTES

  Uses the command "sqlplus".
  Tested with Oracle Database 12c R1.

=head1 AUTHOR

  K.Cima https://github.com/shakemid

=head1 LICENSE

  GPLv2

=cut

# Magic markers
#%# family=contrib
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

# Environments
: ${oracle_auth:=/ as SYSDBA}
: ${ORACLE_SID:=orcl}
: ${ORACLE_HOME:=$( echo /opt/oracle/product/* )}

PATH=$PATH:$ORACLE_HOME/bin
export PATH ORACLE_HOME ORACLE_SID

# Graph settings
fields=(
    wait_buffer_busy_waits
    wait_cursor_mutex_s
    wait_cursor_mutex_x
    wait_cursor_pin_s
    wait_cursor_pin_s_wait_on_x
    wait_cursor_pin_x
    wait_enq_tx_index_contention
    wait_latch_cache_buffers_chains
    wait_latch_row_cache_objects
    wait_latch_shared_pool
    wait_lck0_row_cache_object_free
    wait_libcache_interrupt_action_by_lck
    wait_library_cache_load_lock
    wait_library_cache_lock
    wait_library_cache_pin
    wait_library_cache_mutex_x
    wait_resmgr_internal_state_change
    wait_row_cache_lock
)

# memo: select event from v$system_event where wait_class = 'Concurrency' order by event;

labels=(
    'buffer busy waits'
    'cursor: mutex S'
    'cursor: mutex X'
    'cursor: pin S'
    'cursor: pin S wait on X'
    'cursor: pin X'
    'enq: TX - index contention'
    'latch: cache buffers chains'
    'latch: row cache objects'
    'latch: shared pool'
    'LCK0 row cache object free'
    'libcache interrupt action by LCK'
    'library cache load lock'
    'library cache lock'
    'library cache pin'
    'library cache: mutex X'
    'resmgr:internal state change'
    'row cache lock'
)

types=(
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
)

draws=(
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
    LINE
)


autoconf() {
    if [ -x $( which sqlplus ) ]; then
        echo yes
    else
        echo no
    fi
    exit 0
}

config() {
    echo graph_title Oracle Wait Event - Concurrency
    echo graph_info Oracle Wait Event - Concurrency
    echo graph_category Oracle
    echo graph_args --base 1000 --lower-limit 0 --rigid
    echo graph_vlabel microseconds
    #echo graph_scale no
    echo graph_order ${fields[@]} 

    i=0
    for field in ${fields[@]}
    do
        echo ${field}.label ${labels[$i]}
        echo ${field}.type ${types[$i]}
        echo ${field}.draw ${draws[$i]}
        i=$((i+1))
    done
 
    exit 0
}

getvalue() {
    i=0
    for field in ${fields[@]}
    do
        sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'
set pagesize 0
set linesize 256
set numwidth 30
set feedback off
SELECT
  '${field}.value ' || time_waited_micro
FROM
  v\$system_event
WHERE
  event = '${labels[$i]}';
EOF
        i=$((i+1))
    done
  
    exit 0
}

case $1 in
autoconf)
    autoconf
    ;;
config)
    config
    ;;
*)
    getvalue
    ;;
esac
