#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

  oracle_cachehit - Munin plugin to monitor Oracle Cache Hit Ratio

=head1 CONFIGURATION

  The following shows example settings for this plugin:

  [oracle_*]
     user  oracle
     env.oracle_auth  / as SYSDBA
     env.ORACLE_HOME  /path/to/oracle/product/version
     env.ORACLE_SID   SOMESID

=head1 NOTES

  Uses the command "sqlplus".
  Tested with Oracle Database 12c R1.

=head1 AUTHOR

  K.Cima https://github.com/shakemid

=head1 LICENSE

  GPLv2

=cut

# Magic markers
#%# family=contrib
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

# Environments)
: ${oracle_auth:=/ as SYSDBA}
: ${ORACLE_SID:=orcl}
: ${ORACLE_HOME:=$( echo /opt/oracle/product/* )}

PATH=$PATH:$ORACLE_HOME/bin
export PATH ORACLE_HOME ORACLE_SID


autoconf() {
    if [ -x $( which sqlplus ) ]; then
        echo yes
    else
        echo no
    fi
    exit 0
}

config() {
    echo graph_title Oracle Cache Hit Ratio
    echo graph_category Oracle
    echo graph_args --base 1000 --lower-limit 0 --upper-limit 100 --rigid
    echo graph_vlabel %
    echo graph_info Oracle Cache Hit Ratio
    echo graph_scale no

    echo buf_hitratio.label Buffer Cache Hit Ratio
    echo buf_hitratio.type GAUGE
    echo buf_hitratio.draw LINE

    echo lib_hitratio.label Library Cache Hit Ratio
    echo lib_hitratio.type GAUGE
    echo lib_hitratio.draw LINE

    echo dict_hitratio.label Dictionary Cache Hit Ratio
    echo dict_hitratio.type GAUGE
    echo dict_hitratio.draw LINE
}

getvalue() {

    sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'
set pagesize 0
set linesize 256
set numwidth 30
SELECT
   'buf_hitratio.value ' || round( ( 1 - ( SUM( DECODE( name, 'physical reads cache', value, 0 ) ) /
    ( SUM( DECODE( name, 'consistent gets from cache', value, 0) ) +
      SUM( DECODE( name, 'db block gets from cache', value, 0 ) ) ) ) ) * 100 )
FROM
  v\$sysstat;
EOF

    sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'
set pagesize 0
set linesize 256
set numwidth 30
SELECT
  'lib_hitratio.value ' || round( sum(pins) / ( sum(pins) + sum(reloads) ) * 100 )
FROM
  v\$librarycache;
EOF

    sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'
set pagesize 0
set linesize 256
set numwidth 30
SELECT
  'dict_hitratio.value ' || round( ( 1 - sum(getmisses) / sum(gets) ) * 100 )
FROM
  v\$rowcache;
EOF

}

case $1 in
autoconf)
    autoconf
    ;;
config)
    config
    ;;
*)
    getvalue
    ;;
esac
