#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

  oracle_tablespace - Munin plugin to monitor Oracle Table Space Usage

=head1 CONFIGURATION

  The following shows example settings for this plugin:

  [oracle_*]
     user  oracle
     env.oracle_auth  / as SYSDBA
     env.ORACLE_HOME  /path/to/oracle/product/version
     env.ORACLE_SID   SOMESID

=head1 NOTES

  Uses the command "sqlplus".
  Tested with Oracle Database 12c R1.

=head1 AUTHOR

  K.Cima https://github.com/shakemid

=head1 LICENSE

  GPLv2

=cut

# Magic markers
#%# family=contrib
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

# Environments
: ${oracle_auth:=/ as SYSDBA}
: ${ORACLE_SID:=orcl}
: ${ORACLE_HOME:=$( echo /opt/oracle/product/* )}

PATH=$PATH:$ORACLE_HOME/bin
export PATH ORACLE_HOME ORACLE_SID

# Graph settings
fields=()
labels=()
types=()
draws=()
type_default=GAUGE
draw_default=LINE
: ${warning:=90}
: ${critical:=95}


autoconf() {
    if [ -x $( which sqlplus ) ]; then
        echo yes
    else
        echo no
    fi
    exit 0
}

config() {
    echo graph_title Oracle Table Space Usage
    echo graph_info Oracle Table Space Usage
    echo graph_category Oracle
    echo graph_args --base 1000 --lower-limit 0 --upper-limit 100 --rigid
    echo graph_vlabel %
    #echo graph_scale no
    echo graph_order ${fields[@]}
    echo warning $warning
    echo critical $critical

    i=0
    for field in ${fields[@]}
    do
        echo ${field}.label ${labels[$i]}
        echo ${field}.type  ${types[$i]}
        echo ${field}.draw  ${draws[$i]}
        i=$((i+1))
    done
 
    exit 0
}

getfield() {
    local line
    while read line
    do
        fields+=( "$line" )
        labels+=( "$line" )
        types+=( $type_default )
        draws+=( $draw_default )
    done < <( sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'
set pagesize 0
set linesize 256
set numwidth 30
set feedback off
SELECT
   regexp_replace( tablespace_name, '[^A-Za-z0-9_]', '_' )
FROM
   dba_data_files
ORDER BY
   tablespace_name;
EOF
)

}

getvalue() {
    sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'
set pagesize 0
set feedback off
set linesize 256
set numwidth 30
SELECT
  regexp_replace( tablespace_name, '[^A-Za-z0-9_]', '_' ) || '.value ' || 
  round( (total_bytes - free_total_bytes) / total_bytes * 100, 0 )
FROM
  ( SELECT
      tablespace_name,
      sum(bytes) total_bytes
    FROM
      dba_data_files
    GROUP BY
      tablespace_name
  ),
  ( SELECT
      tablespace_name free_tablespace_name,
      sum(bytes) free_total_bytes
    FROM
      dba_free_space
    GROUP BY 
      tablespace_name
  )
WHERE
  tablespace_name = free_tablespace_name;
EOF
  
    exit 0
}

# main
case $1 in
autoconf)
    autoconf
    ;;
config)
    getfield
    config
    ;;
*)
    getvalue
    ;;
esac
