#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

  oracle_session_wait - Munin plugin to monitor Oracle Session Wait Statistics

=head1 CONFIGURATION

  The following shows example settings for this plugin:

  [oracle_*]
     user  oracle
     env.oracle_auth  / as SYSDBA
     env.ORACLE_HOME  /path/to/oracle/product/version
     env.ORACLE_SID   SOMESID

=head1 NOTES

  Uses the command "sqlplus".
  Tested with Oracle Database 12c R1.

=head1 AUTHOR

  K.Cima https://github.com/shakemid

=head1 LICENSE

  GPLv2

=cut

# Magic markers
#%# family=contrib
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

# Environments
: ${oracle_auth:=/ as SYSDBA}
: ${ORACLE_SID:=orcl}
: ${ORACLE_HOME:=/opt/oracle/product/*}

PATH=$PATH:$ORACLE_HOME/bin
export PATH ORACLE_HOME ORACLE_SID

# Graph settings
fields=()
labels=()
types=()
draws=()
type_default=GAUGE
draw_default=AREASTACK

clean_fieldname2() {
    local temp=$( echo "$@" | tr '[A-Z]' '[a-z]' | sed -e 's/[^a-z0-9_ ]//g' )
    echo $( clean_fieldname "$temp" )
}

getfield() {
    local line
    while read line
    do
        fields+=( wait_$( clean_fieldname2 $line ) )
        labels+=( "$line" )
        types+=( $type_default )
        draws+=( $draw_default )
    done < <( sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'; echo Other; echo Idle;
set pagesize 0
set linesize 256
set numwidth 30
set feedback off
SELECT
  wait_class
FROM
  v\$event_name
WHERE
  wait_class NOT IN ( 'Other', 'Idle' )
GROUP BY
  wait_class
ORDER BY
  wait_class;
EOF
)

}

autoconf() {
    if [ -x $( which sqlplus ) ]; then
        echo yes
    else
        echo no
    fi
    exit 0
}

config() {
    echo graph_title Oracle Session Wait Statistics
    echo graph_info Oracle Session Wait Statistics
    echo graph_category Oracle
    echo graph_args --base 1000 --lower-limit 0 --rigid
    echo graph_vlabel Count
    #echo graph_scale no
    echo graph_order ${fields[@]}

    i=0
    for field in ${fields[@]}
    do
        echo ${field}.label ${labels[$i]}
        echo ${field}.type  ${types[$i]}
        echo ${field}.draw  ${draws[$i]}
        i=$((i+1))
    done
 
    exit 0
}

getvalue() {
    i=0
    for field in ${fields[@]}
    do
        sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'
set pagesize 0
set feedback off
set linesize 256
set numwidth 30
SELECT
  '${field}.value ' || count(wait_class)
FROM
  v\$session
WHERE
  username is not null and wait_class = '${labels[$i]}';
EOF
        i=$((i+1))
    done
  
    exit 0
}

# main
case $1 in
autoconf)
    autoconf
    ;;
config)
    getfield
    config
    ;;
*)
    getfield
    getvalue
    ;;
esac
