#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

  oracle_cursor - Munin plugin to monitor Oracle Cursor Statistics

=head1 CONFIGURATION

  The following shows example settings for this plugin:

  [oracle_*]
     user  oracle
     env.oracle_auth  / as SYSDBA
     env.ORACLE_HOME  /path/to/oracle/product/version
     env.ORACLE_SID   SOMESID

=head1 NOTES

  Uses the command "sqlplus".
  Tested with Oracle Database 12c R1.

=head1 AUTHOR

  K.Cima https://github.com/shakemid

=head1 LICENSE

  GPLv2

=cut

# Magic markers
#%# family=auto
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

# Environments
: ${oracle_auth:=/ as SYSDBA}
: ${ORACLE_SID:=orcl}
: ${ORACLE_HOME:=/opt/oracle/product/*}

PATH=$PATH:$ORACLE_HOME/bin
export PATH ORACLE_HOME ORACLE_SID


autoconf() {
    if [ -x $( which sqlplus ) ]; then
        echo yes
    else
        echo no
    fi
    exit 0
}

config() {
    echo graph_title Oracle Open Cursors
    echo graph_category Oracle
    echo graph_args --base 1000 --lower-limit 0 --rigid
    echo graph_vlabel Count
    echo graph_info Oracle Open Cursors
    #echo graph_scale no

    echo open_cursor.label Open Cursors
    echo open_cursor.type GAUGE
    echo open_cursor.draw LINE
}

getvalue() {
    sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'
set pagesize 0
set linesize 256
set numwidth 30
SELECT
  'open_cursor.value ' || value
FROM
   v\$sysstat
WHERE
  name = 'opened cursors current';
EOF
}

case $1 in
autoconf)
    autoconf
    ;;
config)
    config
    ;;
*)
    getvalue
    ;;
esac
