#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

  oracle_sgainfo - Munin plugin to monitor Oracle SGA

=head1 CONFIGURATION

  The following shows example settings for this plugin:

  [oracle_*]
     user  oracle
     env.oracle_auth  / as SYSDBA
     env.ORACLE_HOME  /path/to/oracle/product/version
     env.ORACLE_SID   SOMESID

=head1 NOTES

  Uses the command "sqlplus".
  Tested with Oracle Database 12c R1.

=head1 AUTHOR

  K.Cima https://github.com/shakemid

=head1 LICENSE

  GPLv2

=cut

# Magic markers
#%# family=auto
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

# Environments
: ${oracle_auth:=/ as SYSDBA}
: ${ORACLE_HOME:=/opt/oracle/product/*}
: ${ORACLE_SID:=orcl}

PATH=$PATH:$ORACLE_HOME/bin
export PATH ORACLE_HOME ORACLE_SID

# Graph settings
fields=(
    maximum_sga_size
    fixed_sga_size
    redo_buffers
    in-memory_area_size
    shared_pool_size
    large_pool_size
    java_pool_size
    streams_pool_size
    shared_io_pool_size
    buffer_cache_size
)

labels=(
    "Maximum SGA Size"
    "Fixed SGA Size"
    "Redo Buffers"
    "In-Memory Area Size"
    "Shared Pool Size"
    "Large Pool Size"
    "Java Pool Size"
    "Streams Pool Size"
    "Shared IO Pool Size"
    "Buffer Cache Size"
)

types=(
    GAUGE
    GAUGE
    GAUGE
    GAUGE
    GAUGE
    GAUGE
    GAUGE
    GAUGE
    GAUGE
    GAUGE
)

draws=(
    LINE
    AREASTACK
    AREASTACK
    AREASTACK
    AREASTACK
    AREASTACK
    AREASTACK
    AREASTACK
    AREASTACK
    AREASTACK
)


autoconf() {
    if [ -x $( which sqlplus ) ]; then
        echo yes
    else
        echo no
    fi
    exit 0
}

config() {
    echo graph_title Oracle SGA Statistics
    echo graph_category Oracle
    echo graph_args --base 1000 --lower-limit 0 --rigid
    echo graph_vlabel Bytes
    echo graph_info Oracle SGA Statistics
    #echo graph_scale no
    echo graph_order ${fields[@]}

    i=0
    for field in ${fields[@]}
    do
        echo ${field}.label ${labels[$i]}
        echo ${field}.type  ${types[$i]}
        echo ${field}.draw  ${draws[$i]}
        i=$((i+1))
    done
 
    exit 0
}

getvalue() {
    i=0
    for field in ${fields[@]}
    do
        sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'
set pagesize 0
set feedback off
set linesize 256
set numwidth 30
SELECT
  '${field}.value ' || bytes 
FROM
  v\$sgainfo 
WHERE
  name = '${labels[$i]}';
EOF
        i=$((i+1))
    done
  
    exit 0
}

case $1 in
autoconf)
    autoconf
    ;;
config)
    config
    ;;
*)
    getvalue
    ;;
esac
