#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

  oracle_event_wait_application - Munin plugin to monitor Oracle Wait Event Statistics

=head1 CONFIGURATION

  The following shows example settings for this plugin:

  [oracle_*]
     user  oracle
     env.oracle_auth  / as SYSDBA
     env.ORACLE_HOME  /path/to/oracle/product/version
     env.ORACLE_SID   SOMESID

=head1 NOTES

  Uses the command "sqlplus".
  Tested with Oracle Database 12c R1.

=head1 AUTHOR

  K.Cima https://github.com/shakemid

=head1 LICENSE

  GPLv2

=cut

# Magic markers
#%# family=contrib
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

# Environments
: ${oracle_auth:=/ as SYSDBA}
: ${ORACLE_SID:=orcl}
: ${ORACLE_HOME:=/opt/oracle/product/*}

PATH=$PATH:$ORACLE_HOME/bin
export PATH ORACLE_HOME ORACLE_SID

# Graph settings
fields=(
    wait_enq_ro_fast_object_reuse
    wait_enq_ko_fast_object_checkpoint
    wait_enq_tm_contention
    wait_enq_tx_row_lock_contention
    wait_sqlnet_break_reset_to_client
)

labels=(
    'enq: RO - fast object reuse'
    'enq: KO - fast object checkpoint'
    'enq: TM - contention'
    'enq: TX - row lock contention'
    'SQL*Net break/reset to client'
)

types=(
    DERIVE
    DERIVE
    DERIVE
    DERIVE
    DERIVE
)

draws=(
    LINE
    LINE
    LINE
    LINE
    LINE
)


autoconf() {
    if [ -x $( which sqlplus ) ]; then
        echo yes
    else
        echo no
    fi
    exit 0
}

config() {
    echo graph_title Oracle Wait Event - Application
    echo graph_category Oracle
    echo graph_args --base 1000 --lower-limit 0 --rigid
    echo graph_vlabel microseconds
    echo graph_info Oracle Wait Event - Application
    #echo graph_scale no
    echo graph_order ${fields[@]} 

    i=0
    for field in ${fields[@]}
    do
        echo ${field}.label ${labels[$i]}
        echo ${field}.type ${types[$i]}
        echo ${field}.draw ${draws[$i]}
        i=$((i+1))
    done
 
    exit 0
}

getvalue() {
    i=0
    for field in ${fields[@]}
    do
        sqlplus -s ${oracle_auth} <<EOF | grep -v '^$'
set pagesize 0
set linesize 256
set numwidth 30
set feedback off
SELECT
  '${field}.value ' || time_waited_micro
FROM
  v\$system_event
WHERE
  event = '${labels[$i]}';
EOF
        i=$((i+1))
    done
  
    exit 0
}

case $1 in
autoconf)
    autoconf
    ;;
config)
    config
    ;;
*)
    getvalue
    ;;
esac
